%% After Adaptation Code - Paper: 
% Writer: Amin M Nasrabadi - Email: amin.m.nasrabadi@gmail.com
% Used for paper: 
% This code will generate a Linear-Quadratic-Regulator (LQR) model for 
% the control of standing balance. We represented body dynamics as an 
% inverted pendulum based on the average anthropometrics of the participants, 
% set passive stiffness at 70% of load stiffness (Loram et al., 2007) 
% and damping ratio at 5.73 Nm·s/rad (Loram & Lakie, 2002). 
% 
% To emulate the physiological control of standing balance, we modeled 
% angular position and angular velocity noises as pink noise based on 
% perceptual thresholds for balance perturbations (RMS values: 0.002 rad 
% and 0.0036 rad/s, respectively) (Fitzpatrick & McCloskey, 1994; 
% Tisserand et al., 2022). The torque generated by the controller was 
% influenced by signal-dependent noise, modeled using bi-linear curves to 
% induce motor noise proportional to torque magnitude. These profiles were 
% informed by isometric experiments measuring ankle torque during 
% plantarflexion and dorsiflexion, which demonstrated distinct motor noise 
% at torque levels below and above 10% of maximum voluntary contraction (Tracy, 2007). 
% 
% We incorporated prediction errors and feedback errors in the control of 
% standing balance. First, we compared the predicted state to the set point 
% at t = t + ΔtL, where t indicates when torque is introduced into the 
% plant (inverted pendulum), subsequently generating both pendulum angular 
% position and velocity to generate an error signal relative to the desired 
% future state (state_hat in the code). Second, we determined the feedback 
% error by comparing the noisy state against controller-predicted delayed 
% states at t = t* - ΔtS (error prediction and beta factor). The two errors 
% were summed and supplied as input to the LQR controller, which then 
% generated an action tailored for the present state, optimized for 
% time t = t* + ΔtM + ΔtR. Then we modeleld standing balance without delays 
% simulation data from the models optimized with no delay (to simulate 
% pre-adaptation; light blue) and with a 250 ms delay (to simulate 
% post-adaptation; black). We directly compared simulated data between the 
% models trained with and without the 250 ms delay by starting the simulations 
% with the same randomization seed. 
%
% This script uses three text files containing noise data to simulate
% variability between human participants. Each text file stores noise
% values corresponding to 30 participants, representing natural variations
% in human sensory and motor responses.  
%
% Specifically:  
%   - two files are used to introduce sensory angle and velocity noises, 
%       modeling the variability of how participants perceive angle and velocity.  
%   - Another file provides action noise, representing differences in how
%     participants execute movements or actions.   
%
% By using these noise profiles, the simulation accounts for realistic
% human variability, improving the robustness and generalizability of the
% model outcomes.

% Initialize parameters
clear
clc
close all


%% Parameters
g = 9.81;   % Gravity constant
m = 67.29;           % Pendulum mass
c = 5.73;          % Pendulum Viscosity
L = 0.8253;
I = m * L^2;

% State Space
A = [0 1; 0.3*m*g*L/I -c/I];
B = [0; 1/I];
C = eye(2);
D = 0;
NameData = 'Paper';


T_d_input = 0.06; % Input delay in seconds to plant (Sensory delay)
T_d_output = 0.06; % Output delay in seconds from plant (Motor delay)
dt = 0.004; % Time step sec
T = 60; % Total simulation time sec
N = T/dt; % Number of time steps
Fs = 250;           % Sampling rate [Hz]
Ns = T*Fs;          % Number of samples in segment duration
f = Fs*(0:(Ns/2))/Ns;

% Noise Coefficients
mn_coeff = 1;
thn_coeff = 0.002;
thdotn_coeff = 0.0036;

motor_noiseTest  = readmatrix("NoiseP1.txt");
th_noiseTest  = readmatrix("NoiseP2.txt");
thdot_noiseTest  = readmatrix("NoiseP3.txt");

mainAddress = pwd;
mainAddress = horzcat(mainAddress,'\');
% For Linux
%mainAddress = horzcat(mainAddress,'/');


train_delays = [0 0.25 0 0.25];
Gain_delays = [0 0.25 0 0.25];
alpha_list = [0 0 0 0];

beta_list = [0.7 0.7 0.55 0.7]; % K coeff
iTrain = 1

alpha = alpha_list(iTrain);
beta = beta_list(iTrain);
%     T_r_delay = train_delays(iTrain);
T_r_delay = 0;


% Transfer function for designing the LQR With Robotic delay
sys_delayed = ss(A, B, C, D, 'InputDelay', T_d_input + Gain_delays(iTrain), 'OutputDelay', T_d_output);
% % Natural delay
% sys_delayed = ss(A, B, C, D, 'InputDelay', T_d_input, 'OutputDelay', T_d_output);

% Padé approximation for the delay
order = 2; % Order of the Padé approximation (adjust as needed)
sys_delayed_approx = pade(sys_delayed, order);

[A_d, B_d, C_d, D_d] = ssdata(sys_delayed_approx);


% Define the state and control weight matrices Q and R
Q_d = eye(size(A_d)); % You may need to adjust the weights based

Q = eye(2); % State weighting matrix
R = 1; % Control weighting matrix

% Solve the continuous-time Algebraic Riccati Equation (CARE)
[P, ~, ~] = care(A, B, Q, R);

% Compute the LQR gain
K2 = R \ B' * P; % Equivalent to K = inv(R) * B' * P

K = lqr(A_d, B_d, Q_d, R);

% The gains for the real dynamics
K = K(5:6);

%% Simulation

% It's not important for this code, mostly used when we want 
iteration = 1; 
% Simulation
for iTrain = 1:size(train_delays,2)

    close all
    alpha = alpha_list(iTrain);
    beta = beta_list(iTrain);
    

    % Transfer function for designing the LQR With Robotic delay
    sys_delayed = ss(A, B, C, D, 'InputDelay', T_d_input + Gain_delays(iTrain), 'OutputDelay', T_d_output);
    % % Natural delay
    % sys_delayed = ss(A, B, C, D, 'InputDelay', T_d_input, 'OutputDelay', T_d_output);
    
    % Padé approximation for the delay
    order = 2; % Order of the Padé approximation (adjust as needed)
    sys_delayed_approx = pade(sys_delayed, order);
    
    [A_d, B_d, C_d, D_d] = ssdata(sys_delayed_approx);
    
    
    % Define the state and control weight matrices Q and R
    Q_d = eye(size(A_d)); % You may need to adjust the weights based
    
    Q = eye(2); % State weighting matrix
    R = 1; % Control weighting matrix
    
    % Solve the continuous-time Algebraic Riccati Equation (CARE)
    [P, ~, ~] = care(A, B, Q, R);
    
    % Compute the LQR gain
    K2 = R \ B' * P; % Equivalent to K = inv(R) * B' * P
    
    K = lqr(A_d, B_d, Q_d, R);

    % The gains for the real dynamics
    K = K(5:6);

    % Time to predict (forward prediction)
    T_d_forward = T_d_output + T_d_input + train_delays(iTrain);
    train_delays(iTrain)
    nForward = (round(T_d_forward/dt));

    Description = horzcat('LQR','ITR',num2str(iteration), ...
                            'DN',num2str((T_d_input + T_d_output)*1000), ...
                            'DR',num2str((T_r_delay)*1000), ...
                            'DT',num2str(train_delays(iTrain)*1000), ...
                            'DG',num2str(Gain_delays(iTrain)*1000), ...
                            'MN',num2str(mn_coeff), ...
                            'TN',num2str(thn_coeff), ...
                            'TDN',num2str(thdotn_coeff), ...
                            'R',num2str(R), ...
                            'QT',num2str(Q(1,1)), ...
                            'QTD',num2str(Q(2,2)), ...
                            'alpha',num2str(alpha), ...
                            'beta',num2str(beta), ...
                            NameData);
        
    mkdir(Description);


    for iTest = 1:30
        
        iTest

        % Initialize variables
        init_angle_rad = 0 * pi / 180; 
        state = [init_angle_rad; 0]; % [theta; theta_dot]
        state_hat = [init_angle_rad; 0]; % Estimated state for Smith Predictor
        u = zeros(1, N); % Control input
        state_hat_history = zeros(2, N);

        for k = 1:N
        
            % State and torque for the predictor
            state_hat = zeros(2,round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt));
            u_hat = zeros(1,round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt));
            state_hat(:,1) = state(:,k);
            state_hat(1,1) = state_hat(1,1) + thn_coeff * th_noiseTest(k,iTest); 
            state_hat(2,1) = state_hat(2,1) + thdotn_coeff * thdot_noiseTest(k,iTest);

            state_hat_error(1,1) = thn_coeff;
            state_hat_error(2,1) = thdotn_coeff; 
            
            % error to actual feedback (the beta factor will be multiplied
            % later)
            if k>(round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt)) && k<N
                error_prediction = state_hat(:,1) - state_hat_history(:,k+1);                
            else
                error_prediction = 0;
            end            

            % Forward Simulation for Smith Predictor
            for iForward = 1:nForward
                if (k+iForward-2)>=(round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt))
                    u_hat(iForward) = -K * (state_hat(:, iForward));
                    u_hat_error(iForward) = abs(u_hat(iForward)) * mn_coeff;                    
                else
                    u_hat(iForward) = 0;
                    u_hat_error(iForward) = 0;                    
                end
                state_hat_dot = A * state_hat(:,iForward) + B * u_hat(iForward);
                state_hat(:, iForward+1) = state_hat(:, iForward) + state_hat_dot * dt;

                state_hat_dot_error = A * state_hat_error(:,iForward) + B * u_hat_error(iForward);
                state_hat_error(:, iForward+1) = state_hat_error(:, iForward) + state_hat_dot_error * dt;        
            end   
            
            % Worst case scenario - a correction for the prediction will be
            % added  - alpha factor - it is set at zero. 
            correction_state_hat(1,1) = sign(state_hat(1,iForward)) * thn_coeff * alpha;
            correction_state_hat(2,1) = sign(state_hat(2,iForward)) * thdotn_coeff * alpha;
            

%             correction_state_hat = correction_state_hat *(1-beta) + error_prediction * beta;
            correction_state_hat = correction_state_hat + error_prediction * beta;

            % LQR implementation
            correction_u_hat = -K * correction_state_hat;

            % LQR control based on Smith Predictor
            if k <= (N-(round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt)))
        %         u(k) = -K * (state_hat(:, end));        
                u(k + (round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt))-1) = u_hat(iForward) + correction_u_hat ;
                state_hat_history(:,k+ (round(T_d_input/dt) + round(T_d_output/dt) + round(T_r_delay/dt))) = state_hat(:, iForward);
            end
        

            torque_final = u(k);

            if torque_final<-256
                torque_final = -256;
            end
            if torque_final>84
                torque_final = 84;                
            end
        
            finaltorque(k) = torque_final*(1 + mn_coeff * custom_TN(torque_final) * motor_noiseTest(k,iTest));
            
            % Dynamic of the system
            state_dot = A * state(:, k) + B * finaltorque(k);
            state(:, k+1) = state(:, k) + state_dot * dt;
            acc_temp(k) = state_dot(2);
        
        end
        
        torque_temp = finaltorque;
        pos_temp = state(1,1:end-1);
        vel_temp = state(2,1:end-1);
        
        % Graphing the amplitude spectrum of velocity
        specturmfirst = fft(vel_temp*180/pi);
        P2first = abs(specturmfirst/Ns);
        P1first = P2first(1:Ns/2+1);
        P1first(2:end-1) = 2*P1first(2:end-1);
        figure('visible','off');
        plot(f(1:100),P1first(1:100),'b*') 
        title('Amplitude spectrum of angle signal')
        xlabel('f (Hz)')
        ylabel('Amplitudes (deg)')
        nameFigure = horzcat('Pendulum_FreqSpec_',num2str(iTest));
        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png')) 
        totalSpectrum (iTrain,iTest,:) = P1first;

        
        % Graphing the amplitude spectrum of torque
        specturmfirst = fft(torque_temp);
        P2first = abs(specturmfirst/Ns);
        P1first = P2first(1:Ns/2+1);
        P1first(2:end-1) = 2*P1first(2:end-1);
        figure('visible','off');
        plot(f(1:100),P1first(1:100),'b*') 
        title('Amplitude spectrum of torque signal')
        xlabel('f (Hz)')
        ylabel('Amplitudes (N.m)')
        nameFigure = horzcat('Torque_FreqSpec_',num2str(iTest));
        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png')) 
        totalSpectrumTorque (iTrain,iTest,:) = P1first;     
        
        
        torque_NOposvel = torque_temp - ...
            ( pos_temp .* (m*g*L) ) - vel_temp*c;
                
        torque_NOvelaccel = torque_temp - acc_temp*I - vel_temp*c;
        
        % Plot results
        sampleShow = N;
        samplePrediction = size(state_hat_history,2);
        time = dt:dt:(sampleShow)*dt;
        timePridiction = dt:dt:(samplePrediction)*dt;
        
        if max(state(1,:)) *180/pi > 20 || ...
                min(state(1,:)) * 180/pi < -20
            result_char = 'f';
        else
            result_char = 's';
        end

        History_result(iTest) = result_char;
        
        figure('visible','off');
        subplot(3, 1, 1);
        plot(time, state(1, 1:sampleShow).*180/pi, 'r', timePridiction, state_hat_history(1, :).*180/pi, 'b');
        legend('Actual theta', 'Estimated theta (Smith Predictor)');
        xlim ([0 60])
%         ylim ([-3 6])
        xlabel('Time (s)');
        ylabel('Angle (deg)');
        title('Inverted Pendulum with Smith Predictor and LQR');
        nameFigure = horzcat('Pendulum_Behaviour_',num2str(iTest),...
            result_char);
        subplot(3, 1, 2);
        plot(time, finaltorque(1:sampleShow), 'g');
        legend('Control Input (N.m)');
        xlabel('Time (s)');
        ylabel('Control Input');
        subplot(3, 1, 3);
        plot(time, state(1, 1:sampleShow).*180/pi, 'r');
        legend('Actual theta');
        xlim ([0 60])
%         ylim ([-3 6])
        xlabel('Time (s)');
        ylabel('Angle (deg)');

        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png')) 



        state_torque(1:2,:) = state(:,1:end-1);
        state_torque(3,:) = finaltorque;
        save(formatFile,'state_torque')
        
        signal1 = acc_temp((floor(T_r_delay/dt))+1:sampleShow)*180/pi;
        signal2 = torque_NOposvel(1:sampleShow-floor(T_r_delay/dt));
        
        corrSignal = xcorr(pos_temp(floor(T_r_delay/dt)+1:sampleShow)*180/pi, ...
            torque_NOvelaccel(1:sampleShow-floor(T_r_delay/dt)),'unbiased');
        corrSignal2 = xcorr(signal1, signal2,'unbiased');

        figure('visible','off');
        x0=300;
        y0=300;
        width=500;
        height=400;  
        set(gcf,'position',[x0,y0,width,height])   
        plot(acc_temp,torque_NOposvel)

        nameFigure = horzcat('TorqueAcceleration',num2str(iTest),...
            result_char);
        title(nameFigure,'fontsize',15)
        xlabel('Acceleration (deg/sec^2)','fontsize',12)
        ylabel('Torque (N.m)','fontsize',12) 
        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png'))  

        tCorr = numel(corrSignal);
        time = dt:dt:dt*tCorr;
        time = time - dt*tCorr/2;
        figure('visible','off');
        x0=300;
        y0=300;
        width=800;
        height=350;  
        set(gcf,'position',[x0,y0,width,height])   
        plot(time,corrSignal)
        [maxCorr, Ind] = min(corrSignal);
        Ind = (Ind - tCorr/2)*dt;
        text(Ind, maxCorr, ['(', num2str(Ind), ', ', num2str(maxCorr), ')'], 'VerticalAlignment', 'bottom');
        nameFigure = horzcat('CrossCorrTorqueAngleCTorqueOut',num2str(iTest),...
            result_char);
        title(nameFigure,'fontsize',15)
        xlabel('Time samples','fontsize',12)
        ylabel('CrossCorrTorqueAngle','fontsize',12) 
        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png'))  
        
        
        tCorr = numel(corrSignal2);
        time = dt:dt:dt*tCorr;
        time = time - dt*tCorr/2;
        figure('visible','off');
        x0=300;
        y0=300;
        width=800;
        height=350;  
        set(gcf,'position',[x0,y0,width,height])
        plot(time,corrSignal2)
        [maxCorr, Ind] = max(corrSignal2);
        Ind = (Ind-tCorr/2)*dt;
        text(Ind, maxCorr, ['(', num2str(Ind), ', ', num2str(maxCorr), ')'], 'VerticalAlignment', 'top');
        nameFigure = horzcat('CrossCorr-TorqueAcceleration-',num2str(iTest),...
            result_char);
        title(nameFigure,'fontsize',15)
        xlabel('Time samples','fontsize',12)
        ylabel('CrossCorrTorqueAcc','fontsize',12) 
        formatFile = horzcat(mainAddress, Description, '\', ...
            nameFigure);
        saveas(gcf,horzcat(formatFile,'.png')) 


        window_size = 10/dt;

        % Number of windows
        num_windows = floor(length(signal1) / window_size);

        cc_results = zeros( num_windows, 2*window_size-1);
        cc_results_norm = zeros( num_windows, 2*window_size-1);
       
        % Compute cross-correlation for each window
        for i = 1:num_windows
            start_idx = (i-1)*window_size + 1;
            end_idx = i*window_size;
            
            segment1 = signal1(start_idx:end_idx);
            segment2 = signal2(start_idx:end_idx);
            
            cc_results(i, :) = xcorr(segment1, segment2,'unbiased');
            cc_results_norm(i, :) = cc_results(i, :) ./ max(cc_results(i,:));
        end
        CCNormal(iTest,:) = cc_results_norm(i, :) ;
        CCNonNormal(iTest,:) = cc_results(i, :) ;
        coRRLength = floor(numel(corrSignal2)/2);

        corrSignals(iTest,:) = corrSignal2(coRRLength-4000:coRRLength+4000);

    end
    corrSignalsMean(iTrain,:) = mean(corrSignals);
    corrSignalsLast(iTrain,:) = corrSignals(iTest,:);
    TrainCC(iTrain,:) = mean(CCNormal(find(History_result == 's'),:));
%     TrainCC(iTrain,:) = CCNormal(iTest,:);

    TrainCCNonNormal(iTrain,:)=mean(CCNonNormal(find(History_result == 's'),:));
    TrainCCstdNonNormal(iTrain,:)=std(CCNonNormal(find(History_result == 's'),:));
    ssStudy = CCNonNormal(find(History_result == 's'),:);
    nLoop = size(ssStudy,1);
    for iLoop = 1:nLoop
        [~,peakTimeData(iLoop)] = max(ssStudy(iLoop,:));
    end
    timePeakStd(iTrain) = std(peakTimeData);

end


%% Frequency spectrum for angle 
% Plotting the traces
f2 = figure;
set(f2, 'Position', [100, 0, 800, 600]); % [left, bottom, width, height]
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
freqPlot = 600;

for i = 1:4
    totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 1
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvg(i,13:12:freqPlot).^2, ...
            'color', [105,169,247]./255, 'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 2
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvg(i,13:12:freqPlot).^2, ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end

ylim([0 0.1])
yticks([10E-6 10E-4 0.1])

title('Velocity auto spectra - matched k = 0.7');
xlabel('Frequency (Hz)');
ylabel({'Angular velocity',['autospectra (', char(176), '/s)^2']}, 'Interpreter', 'tex');
%    num2str(Gain_delays(2) * 1000), 'Location','southeast');
%    num2str(Gain_delays(3) * 1000), ...
lgd = legend('Baseline','Post-Adaptation', 'Location','northwest');
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers
box off

insetPosition2 = [0.42, 0.51, 0.45, 0.35];
axes('Position', insetPosition2);
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
for i = 1:4
    totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 3
        semilogy(f(13:12:freqPlot),totalSpectrumAvg(i,13:12:freqPlot).^2, ...
            'color',[105,169,247]./255, 'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 4
        semilogy(f(13:12:freqPlot),totalSpectrumAvg(i,13:12:freqPlot).^2, ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
ylim([0 0.1])
yticks([10E-6 10E-4 0.1])
% plot(t_inset2, y_inset2, 'c', LineWidth=1);
box off
title('Velocity auto spectra: k_{0} = 0.55, k_{250} = 0.7', 'Interpreter', 'tex');
xlabel('Frequency (Hz)');
ylabel({'Angular velocity',['autospectra (', char(176), '/s)^2']}, 'Interpreter', 'tex');
set(gca, 'FontSize', 12); % Set font size to 12 for axis 
box off
lgd.Box = 'off';

exportgraphics(f2,'FigSpectrum.pdf','ContentType','vector','BackgroundColor','none')


%% Frequency spectrum for torque 

% Plotting the traces
f3 = figure;
set(f3, 'Position', [100, 0, 800, 600]); % [left, bottom, width, height]
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
freqPlot = 600;
for i = 1:4
    totalSpectrumAvgTrq(i,:) = mean(totalSpectrumTorque(i,:,:),2);
    if i == 1
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 2
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
ylim([0 0.5])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers


title('Torque autospectra: matched k = 0.7');
xlabel('Frequency (Hz)');
ylabel({'Ankle torque','autospectra (N.m)^2'}, 'Interpreter', 'tex');
% lgd = legend(mainPlot([1 2]),horzcat('Learned by delay(ms) ',num2str(Gain_delays(1))), ...
%    num2str(Gain_delays(2) * 1000), 'Position',[0.8, 0.3 0.1 0.1]);
lgd = legend('Baseline','Post-Adaptation', 'location', 'northwest');
%    num2str(Gain_delays(3) * 1000), ...
lgd.Box = 'off';
box off

insetPosition2 = [0.42, 0.51, 0.45, 0.35];
axes('Position', insetPosition2);
set(gca, 'YScale', 'log')
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
for i = 1:4
%     totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 3
        semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [105,169,247]./255, 'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 4
        semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
        'color',[26,37,49]./255 , 'LineWidth', 3); % Last trace in bold blue
    end
end
% plot(t_inset2, y_inset2, 'c', LineWidth=1);
box off
title('Torque autospectra: k_{0} = 0.55, k_{250} = 0.7', 'Interpreter', 'tex');
xlabel('Frequency (Hz)');
ylabel({'Ankle torque','autospectra (N.m)^2'}, 'Interpreter', 'tex');
ylim([0 0.5])
yticks([10E-4 10E-3 0.1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers
box off
lgd.Box = 'off';


exportgraphics(f3,'FigTorqueSpectrum.pdf','ContentType','vector','BackgroundColor','none')


%% Frequency spectrum for torque 

state_torqueND7 = load('Pendulum_Behaviour_19ND7.mat');
state_torqueND55 = load('Pendulum_Behaviour_19ND55.mat');
state_torqueWD7 = load('Pendulum_Behaviour_19WD7.mat');

trajectorySamples(1,:) = state_torqueND7.state_torque(1,:).*180/pi;
trajectorySamples(2,:) = state_torqueWD7.state_torque(1,:).*180/pi;
trajectorySamples(3,:) = state_torqueND55.state_torque(1,:).*180/pi;
trajectorySamples(4,:) = state_torqueWD7.state_torque(1,:).*180/pi;

%%
Fs = 15000/60;
dt = 1/Fs;
time = dt:dt:60;
% Plotting the traces
f3 = figure;
set(f3, 'Position', [100, 0, 800, 600]); % [left, bottom, width, height]
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
freqPlot = 600;
for i = 1:4
    if i == 1
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 2
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
ylim([-0.3 1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers


title('Inverted pendulum: matched k = 0.7');
xlabel('time (s)');
ylabel('Angle (deg)');
% lgd = legend(mainPlot([1 2]),horzcat('Learned by delay(ms) ',num2str(Gain_delays(1))), ...
%    num2str(Gain_delays(2) * 1000), 'Position',[0.8, 0.3 0.1 0.1]);
lgd = legend('Baseline','Post-Adaptation', 'location', 'northwest');
%    num2str(Gain_delays(3) * 1000), ...
lgd.Box = 'off';
box off

insetPosition2 = [0.42, 0.58, 0.45, 0.28];
axes('Position', insetPosition2);
set(gca, 'YScale', 'log')
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
for i = 1:4
%     totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 3
        plot(time,trajectorySamples(i,:), ...
            'color', [105,169,247]./255, 'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 4
        plot(time,trajectorySamples(i,:), ...
        'color',[26,37,49]./255 , 'LineWidth', 3); % Last trace in bold blue
    end
end
% plot(t_inset2, y_inset2, 'c', LineWidth=1);
box off
title('Inverted pendulum: k_{0} = 0.55, k_{250} = 0.7', 'Interpreter', 'tex');
xlabel('time (s)');
ylabel('Angle (deg)');
ylim([-0.4 0.4])
% yticks([10E-4 10E-3 0.1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers
box off
lgd.Box = 'off';


exportgraphics(f3,'GraphTrajectories.pdf','ContentType','vector','BackgroundColor','none')

%%

% Plotting the traces
f3 = figure;
set(f3, 'Position', [100, 0, 800, 600]); % [left, bottom, width, height]
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
freqPlot = 600;
for i = 1:4
    totalSpectrumAvgTrq(i,:) = totalSpectrumTorque(i,19,:);
    if i == 1
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 2
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
ylim([-0.3 1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers


title('Inverted pendulum: matched k = 0.7');
xlabel('time (s)');
ylabel('Angle (deg)');
% lgd = legend(mainPlot([1 2]),horzcat('Learned by delay(ms) ',num2str(Gain_delays(1))), ...
%    num2str(Gain_delays(2) * 1000), 'Position',[0.8, 0.3 0.1 0.1]);
lgd = legend('Baseline','Post-Adaptation', 'location', 'northwest');
%    num2str(Gain_delays(3) * 1000), ...
lgd.Box = 'off';
box off

insetPosition2 = [0.42, 0.58, 0.45, 0.28];
axes('Position', insetPosition2);
set(gca, 'YScale', 'log')
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
for i = 1:4
%     totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 1
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 2
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
% plot(t_inset2, y_inset2, 'c', LineWidth=1);
box off
title('Torque autospectra: matched k = 0.7');
xlabel('Frequency (Hz)');
ylabel({'Ankle torque','autospectra (N.m)^2'}, 'Interpreter', 'tex');
ylim([0 0.5])
yticks([10E-4 10E-3 0.1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers
box off
lgd.Box = 'off';


exportgraphics(f3,'TrajectoryMatched.pdf','ContentType','vector','BackgroundColor','none')


%%

% Plotting the traces
f3 = figure;
set(f3, 'Position', [100, 0, 800, 600]); % [left, bottom, width, height]
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
freqPlot = 600;
for i = 1:4
    totalSpectrumAvgTrq(i,:) = totalSpectrumTorque(i,19,:);
    if i == 3
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 4
        mainPlot(i) = plot(time,trajectorySamples(i,:), ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
ylim([-0.3 1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers


title('Inverted pendulum: k_{0} = 0.55, k_{250} = 0.7', 'Interpreter', 'tex');
xlabel('time (s)');
ylabel('Angle (deg)');
% lgd = legend(mainPlot([1 2]),horzcat('Learned by delay(ms) ',num2str(Gain_delays(1))), ...
%    num2str(Gain_delays(2) * 1000), 'Position',[0.8, 0.3 0.1 0.1]);
lgd = legend('Baseline','Post-Adaptation', 'location', 'northwest');
%    num2str(Gain_delays(3) * 1000), ...
lgd.Box = 'off';
box off

insetPosition2 = [0.42, 0.58, 0.45, 0.28];
axes('Position', insetPosition2);
set(gca, 'YScale', 'log')
box off
% legend('0 ms', '100 ms', '200 ms', '250 ms', '300 ms', '350 ms')
for i = 1:4
%     totalSpectrumAvg(i,:) = mean(totalSpectrum(i,:,:),2);
    if i == 3
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [105,169,247]./255,'LineWidth', 3); % First trace in bold black
        hold on
    elseif i == 4
        mainPlot(i) = semilogy(f(13:12:freqPlot),totalSpectrumAvgTrq(i,13:12:freqPlot).^2, ...
            'color', [26,37,49]./255, 'LineWidth', 3); % Last trace in bold blue
    end
end
% plot(t_inset2, y_inset2, 'c', LineWidth=1);
box off
title('Torque autospectra: k_{0} = 0.55, k_{250} = 0.7', 'Interpreter', 'tex');
xlabel('Frequency (Hz)');
ylabel({'Ankle torque','autospectra (N.m)^2'}, 'Interpreter', 'tex');
ylim([0 0.5])
yticks([10E-4 10E-3 0.1])
set(gca, 'FontSize', 12); % Set font size to 12 for axis numbers
box off
lgd.Box = 'off';


exportgraphics(f3,'TrajectoryUnMatched.pdf','ContentType','vector','BackgroundColor','none')

%%

function TNoise = custom_TN(TorqueInput)
    if TorqueInput <0
        sign = -1;
    else
        sign = 1;
    end
    if sign == -1
        MVC = TorqueInput/256;
        if  MVC < 10
            TNoise = 0.021 * MVC + 0.121;
        else
            TNoise = 0.042 * MVC - 0.109;
        end
    else
        MVC = TorqueInput/84;
        if  MVC < 30
            TNoise = 0.013 * MVC + 0.058;
        else
            TNoise = 0.021 * MVC - 0.182;
        end
    end
end